version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-server
    ports:
      - "${WEB_APP_PORT}:${WEB_APP_PORT}"
    environment:
      - OPENFGA_API_URL=http://openfga:${OPENFGA_API_PORT}
    depends_on:
      - openfga
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WEB_APP_PORT}/health"]
      interval: 10s
      timeout: 2s
      retries: 3
    networks:
      - app-network
  openfga:
    image: openfga/openfga:latest
    container_name: openfga
    user: nonroot
    ports:
      - "${OPENFGA_API_PORT}:8080"
      - "${OPENFGA_GRPC_PORT}:8081"
      - "3000:3000"
    # you can check playground in http://localhost:3000/playground
    command: run --playground-enabled --playground-port 3000
    environment:
      - OPENFGA_DATASTORE_ENGINE=memory
      - OPENFGA_LOG_LEVEL=debug
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
